## Задание 1. Использование команд библиотеки NumPy

In [71]:
import numpy as np

### 1.1.	Создаем одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [72]:
my_array = np.linspace(5,100,20)
my_array


array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

### 2.1. Массив с числами кратными 10 и получение из него двумерного массива (3.1.)

In [73]:
my_array = np.array([x for x in my_array if x % 10 == 0])
my_array = my_array.reshape(5,2) #получение двумерного массива с двумя столбцами
my_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])


### 4.1.	Получим набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [74]:
my_second_array = my_array - 5
my_second_array

array([[ 5., 15.],
       [25., 35.],
       [45., 55.],
       [65., 75.],
       [85., 95.]])

### 5.1.	Соединим массивы my_array2 и my_second_array горизонтально. Используйте .T для транспонирования матрицы.

In [75]:
result_matrix = np.concatenate((my_array, my_second_array), axis=1)
my_array = np.delete(my_array.T,[4], axis=1)
print("Исходный массив my_array:")
print(my_array)
print("\nИсходный массив my_second_array:")
print(my_second_array)
print("\nРезультат после объединения и транспонирования:")
print(result_matrix)
result_matrix.shape

Исходный массив my_array:
[[10. 30. 50. 70.]
 [20. 40. 60. 80.]]

Исходный массив my_second_array:
[[ 5. 15.]
 [25. 35.]
 [45. 55.]
 [65. 75.]
 [85. 95.]]

Результат после объединения и транспонирования:
[[ 10.  20.   5.  15.]
 [ 30.  40.  25.  35.]
 [ 50.  60.  45.  55.]
 [ 70.  80.  65.  75.]
 [ 90. 100.  85.  95.]]


(5, 4)

### 6.1.	Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [76]:
result_matrix[1:3] = result_matrix[1:3] / my_array[:4]

print(result_matrix)


[[ 10.          20.           5.          15.        ]
 [  3.           1.33333333   0.5          0.5       ]
 [  2.5          1.5          0.75         0.6875    ]
 [ 70.          80.          65.          75.        ]
 [ 90.         100.          85.          95.        ]]


### 7.1.	Оставить только те значения, которые не изменились после деления


In [77]:
new_combined = np.delete(result_matrix, np.where(np.any(result_matrix < 3, axis=1)), axis=0)
new_combined


array([[ 10.,  20.,   5.,  15.],
       [ 70.,  80.,  65.,  75.],
       [ 90., 100.,  85.,  95.]])

### 8.1 Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [78]:
result_3_rows = new_combined[:, :3]
result_3_rows[[0, 2]] = result_3_rows[[2, 0]]
print(result_3_rows)


[[ 90. 100.  85.]
 [ 70.  80.  65.]
 [ 10.  20.   5.]]


### 9.1 Получить среднее, медиану и стандартное отклонение для каждой строки

In [79]:
row_means = np.mean(result_3_rows, axis=1)
row_medians = np.median(result_3_rows, axis=1)
row_stdevs = np.std(result_3_rows, axis=1)
print("Среднее значение:", row_means)
print("Медиана:", row_medians)
print("Отклонение",+ row_stdevs)

Среднее значение: [91.66666667 71.66666667 11.66666667]
Медиана: [90. 70. 10.]
Отклонение [6.23609564 6.23609564 6.23609564]


### 10.1 Сделать нормализацию на максимальное значение вдоль строк


In [80]:
normalized_result = result_3_rows / np.max(result_3_rows, axis=1, keepdims=True)
print(normalized_result)


[[0.9    1.     0.85  ]
 [0.875  1.     0.8125]
 [0.5    1.     0.25  ]]


# 2.	Использование команд библиотеки pandas

In [81]:
import pandas as pd #импортируем пандас

In [82]:
df = pd.read_csv("Global Population Trends(2016-2022).csv")

### 2.2.	 Считайте несколько первых записей таблицы (head())

In [83]:
print("Несколько первых записей: ")
print(df.head())

Несколько первых записей: 
       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0        

### 2.3. Определите размерность данного фрейма (shape())

In [84]:
print("Размерность данного фрейма ", df.shape)


Размерность данного фрейма  (1073, 12)


### 2.4.	 Выведите название заголовков столбцов фрейма (columns)

In [85]:
print("Название заголовков столбцов фрейма :")
print(df.columns)

Название заголовков столбцов фрейма :
Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


### 2.5.	Получите описание всех переменных (полей) (info())

In [86]:
print("Описание всех переменных:")
print(df.info())

Описание всех переменных:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB
None


### 2.6.	 Удалите строки, не содержащие значения в столбце «Total Population» - “-” 

In [87]:
df1 = df[df['Total Population'] != '-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

In [88]:
for column in df1.columns:
    df1 = df1[df1[column]!='-']
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 561 entries, 1 to 1071
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                561 non-null    object 
 1   Year                   561 non-null    int64  
 2   Total Population       561 non-null    object 
 3   Urban Population       561 non-null    object 
 4   Rural Population       561 non-null    object 
 5   Population Density     561 non-null    object 
 6   Life Expectancy        561 non-null    object 
 7   Birth Rate             561 non-null    float64
 8   Death Rate             561 non-null    float64
 9   Fertility Rate         561 non-null    object 
 10  Infant Mortality Rate  561 non-null    object 
 11  Growth Rate            561 non-null    object 
dtypes: float64(2), int64(1), object(9)
memory usage: 57.0+ KB


In [89]:
df1['Total Population'] = df1['Total Population'].map(lambda x: x.replace(',', '')).astype(int)
df1['Urban Population'] = df1['Urban Population'].map(lambda x: x.replace(',', '')).astype(int)
df1['Rural Population'] = df1['Rural Population'].map(lambda x: x.replace(',', '')).astype(int)
df1['Population Density'] = df1['Population Density'].map(lambda x: x.replace(',', '')).astype(int)
df1['Life Expectancy'] = df1['Life Expectancy'].map(lambda x: x).astype(float)
df1['Fertility Rate'] = df1['Fertility Rate'].map(lambda x: x).astype(float)
df1['Infant Mortality Rate'] = df1['Infant Mortality Rate'].map(lambda x: x).astype(float)
df1['Growth Rate'] = df1['Growth Rate'].map(lambda x: x).astype(float)

df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 561 entries, 1 to 1071
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                561 non-null    object 
 1   Year                   561 non-null    int64  
 2   Total Population       561 non-null    int32  
 3   Urban Population       561 non-null    int32  
 4   Rural Population       561 non-null    int32  
 5   Population Density     561 non-null    int32  
 6   Life Expectancy        561 non-null    float64
 7   Birth Rate             561 non-null    float64
 8   Death Rate             561 non-null    float64
 9   Fertility Rate         561 non-null    float64
 10  Infant Mortality Rate  561 non-null    float64
 11  Growth Rate            561 non-null    float64
dtypes: float64(6), int32(4), int64(1), object(1)
memory usage: 48.2+ KB


### 2.7.	Получите описательную статистику по переменным (например, max(), min(), describe())

In [90]:
print("Описательная статистика по переменным")
print(df.describe())

Описательная статистика по переменным
              Year   Birth Rate   Death Rate
count  1073.000000  1073.000000  1073.000000
mean   2019.013048    18.801519     7.841907
std       1.410190     9.903449     2.973418
min    2017.000000     0.000000     0.000000
25%    2018.000000    10.620000     6.067000
50%    2019.000000    16.025000     7.396000
75%    2020.000000    25.921000     9.313000
max    2021.000000    46.351000    21.700000


### 2.8.	Выполните сортировку данных по нескольким критериям

In [91]:
sorted_df = df.sort_values(by=['Country', 'Year'])
print(sorted_df.head())

       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           - 

### 2.9.	 Выведите название страны, которая имеет максимальную численность населения

In [92]:
df1.loc[df1['Total Population'] == df1['Total Population'].max()]



Country  Year  Total Population  Urban Population  Rural Population  \
204   China  2020        1411100000         866810508         544289492   

     Population Density  Life Expectancy  Birth Rate  Death Rate  \
204                 150             78.0        8.52        7.07   

     Fertility Rate  Infant Mortality Rate  Growth Rate  
204           1.281                    5.5          0.0

### Минимальная численность

In [93]:
df1.loc[df1['Total Population'] == df1['Total Population'].min()]


Country  Year  Total Population  Urban Population  Rural Population  \
994  Tuvalu  2018             10865              6778              4087   

     Population Density  Life Expectancy  Birth Rate  Death Rate  \
994                 362             64.0      23.508      10.107   

     Fertility Rate  Infant Mortality Rate  Growth Rate  
994           3.209                   20.0          0.0

### 2.11 Экспорт фрейма в MS Excel

In [94]:
df.to_excel("Global_Population_Trends_2016-2022.xlsx", index=False)
print("Экспортировано в 'Population_Trends_2016-2022.xlsx'")

Экспортировано в 'Population_Trends_2016-2022.xlsx'
